# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  schedule:
    # Runs every Sunday at 8:00 PM
    - cron: "0 20 * * 0"
    # Runs every weekday at 8:00 AM
    - cron: "0 8 * * 1-5"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set environment variable at the job level
env:
  GoogleServiceApi: ${{ secrets.GoogleServiceApi }}
  
# A workflow run is made up of two jobs
jobs:

  run_file1:
    # This job runs on Sunday at 8:00 PM
    if: github.event.schedule == '0 20 * * 0'
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs file1.py
      - name: Run file1.py
        run: python file1.py

  run_file2:
    # This job runs every weekday at 8:00 AM
    if: github.event.schedule == '0 8 * * 1-5'
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs file2.py
      - name: Run file2.py
        run: python file2.py
